version: "3.9"

services:

  db:
    image: postgres:14
    # restart: always
    environment:
      - POSTGRES_USER=grubberbot@grubberbot.iam
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=grubber
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  dev:
    build:
      context: .
      target: dev
    ports:
      - 8001:5001
    image: grubberbot:dev
    volumes:
      - ./:/app
    depends_on:
      - db

  test:
    build:
      context: .
      target: test
    ports:
      - 8000:5000
    image: grubberbot:test
    volumes:
      - ./:/app
    depends_on:
      - db
      - dev

volumes:
  db:
    driver: local
