version: "3.9"

services:

  bot:
    build:
      context: .
      target: bot
    ports:
      - 8000:5000
    image: grubberbot:bot
    volumes:
      - ./:/app

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=grubberbot@grubberbot.iam
      - POSTGRES_PASSWORD=example
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    external: true
    driver: local
