services:

  dev:
    build:
      context: .
      target: dev
    image: grubberbot:dev
    container_name: grubberbot_dev_container
    volumes:
      - type: bind
        source: .
        target: /repo
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
