version: "3.9"


services:

  db:
    image: postgres:14
    # restart: always
    environment:
      - POSTGRES_USER=grubberbot@grubberbot.iam
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=grubber
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  test:
    build:
      context: .
      target: test
      args:
        - DOCKER_PYTHON_VERSION=${DOCKER_COMPOSE_PYTHON_VERSION:-3.9}
    ports:
      - 8001:5001
    image: grubberbot:test-${DOCKER_COMPOSE_PYTHON_VERSION:-3.9}
    volumes:
      - ./:/app
    depends_on:
      - db

volumes:
  db:
    driver: local
