# Run python unit tests

name: tests

on:
  push:
  pull_request:
  schedule:
    - cron:  "0 0 * * 1"
      branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Docker
      run: docker build --target base -t grubberbot:base .

    - name: Build docker-compose to run unit tests
      run: docker-compose up --build

    - name: Check running containers
      run: docker ps -a
