# Run python unit tests

name: tests

on:
  push:
  pull_request:
  schedule:
    - cron:  "0 0 * * 1"
      branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]
      fail-fast: false

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Python Version
      run: export DOCKER_COMPOSE_PYTHON_VERSION=${{ matrix.python-version }}

    - name: Check Python Version
      run: echo $DOCKER_COMPOSE_PYTHON_VERSION

    - name: Cache Docker
      run: docker-compose -f docker-compose-test.yml build

    - name: Run Tests
      run: docker-compose -f docker-compose-test.yml up --exit-code-from test

    - name: Check running containers
      run: docker ps -a
